### ISSUE TITLE
Support for reading from file

### ISSUE THREAD

**Issue by whereiswolf** [lukix/input-reader#2]
The library only allows for parsing the data in a `string` variable, however I think it should also support reading the data file. So for example to avoid reading the file:
```javascript
const reader = require('input-reader');
const fs = require('fs');

const rawData = fs.readFileSync('./in/a_example.in').toString();
const pattern = `
  rows columns minIngredients maxCells
  ...pizza[]
`;

const data = reader(rawData, pattern)

console.log(reader(data, pattern));
```
we could do this:
```javascript
const reader = require('input-reader');

const pattern = `
  rows columns minIngredients maxCells
  ...pizza[]
`;
const data = reader('./in/a_example.in', pattern, { file: true })

console.log(reader(data, pattern));
```
Or something similiar :D

**Comment by lukix** [comment]
I'm still not sure if it makes sense to include this feature in the library.
Probably I should have called it `input-parser` instead of `input-reader` :)
